# Accelerometer status
# detailed information on Accelerometer systems status
# custom accel_bit_status_t
	bool accel_status_Accel_Register_Read_Back_X  # Accel Register Read Back X
	bool accel_status_Accel_Register_Read_Back_Y  # Accel Register Read Back Y
	bool accel_status_Accel_Register_Read_Back_Z  # Accel Register Read Back Z
	bool accel_status_Accel_Temperature_X  # Accel Temperature X
	bool accel_status_Accel_Temperature_Y  # Accel Temperature Y
	bool accel_status_Accel_Temperature_Z  # Accel Temperature Z
	bool accel_status_Accel_Sensor_X  # Accel Sensor X
	bool accel_status_Accel_Sensor_Y  # Accel Sensor Y
	bool accel_status_Accel_Sensor_Z  # Accel Sensor Z
	bool accel_status_Accel_AC_Stim_X  # Accel AC Stim X
	bool accel_status_Accel_AC_Stim_Y  # Accel AC Stim Y
	bool accel_status_Accel_AC_Stim_Z  # Accel AC Stim Z
	bool accel_status_Accel_Analog_Continuity_X  # Accel Analog Continuity X
	bool accel_status_Accel_Analog_Continuity_Y  # Accel Analog Continuity Y
	bool accel_status_Accel_Analog_Continuity_Z  # Accel Analog Continuity Z
	bool accel_status_Accel_Bypass_X  # Accel Bypass X
	bool accel_status_Accel_Bypass_Y  # Accel Bypass Y
	bool accel_status_Accel_Bypass_Z  # Accel Bypass Z
	bool accel_status_Accel_Level_X  # Accel Level X
	bool accel_status_Accel_Level_Y  # Accel Level Y
	bool accel_status_Accel_Level_Z  # Accel Level Z
