# Gyroscope status
# detailed information on Gyroscope systems status
# custom gyro_bit_status_t
	bool gyro_status_Gyro_Run_X  # Gyro Run X
	bool gyro_status_Gyro_Run_Y  # Gyro Run Y
	bool gyro_status_Gyro_Run_Z  # Gyro Run Z
	bool gyro_status_Gyro_Register_Read_Back_X  # Gyro Register Read Back X
	bool gyro_status_Gyro_Register_Read_Back_Y  # Gyro Register Read Back Y
	bool gyro_status_Gyro_Register_Read_Back_Z  # Gyro Register Read Back Z
	bool gyro_status_Gyro_Temperature_X  # Gyro Temperature X
	bool gyro_status_Gyro_Temperature_Y  # Gyro Temperature Y
	bool gyro_status_Gyro_Temperature_Z  # Gyro Temperature Z
	bool gyro_status_Gyro_AGC_X  # Gyro AGC X
	bool gyro_status_Gyro_AGC_Y  # Gyro AGC Y
	bool gyro_status_Gyro_AGC_Z  # Gyro AGC Z
	bool gyro_status_Gyro_Motor_Bias_X  # Gyro Motor Bias X
	bool gyro_status_Gyro_Motor_Bias_Y  # Gyro Motor Bias Y
	bool gyro_status_Gyro_Motor_Bias_Z  # Gyro Motor Bias Z
	bool gyro_status_Gyro_NVREF_X  # Gyro NVREF X
	bool gyro_status_Gyro_NVREF_Y  # Gyro NVREF Y
	bool gyro_status_Gyro_NVREF_Z  # Gyro NVREF Z
	bool gyro_status_Gyro_Sensor_X  # Gyro Sensor X
	bool gyro_status_Gyro_Sensor_Y  # Gyro Sensor Y
	bool gyro_status_Gyro_Sensor_Z  # Gyro Sensor Z
