# Mission Computer Board Built-in test results
# custom mcb_bit_status_t
	bool mcb_INS_Executable_Code_CRC  # INS Executable Code CRC
	bool mcb_INS_Configuration_File_CRC  # INS Configuration File CRC
	bool mcb_Coefficient  # Coefficient Table CRC
	bool mcb_IMU_Configuration_Table_CRC  # IMU Configuration Table CRC
	bool mcb_IMU_Normal_Mode_Code_CRC  # IMU Normal Mode Code CRC
	bool mcb_External_IMU_GFR_Sync  # External IMU GFR Sync
	bool mcb_External_IMU_CFR_Sync  # External IMU CFR Sync
	bool mcb_IMU_FPGA  # IMU FPGA
	bool mcb_IMU_Serial_Communications  # IMU Serial Communications
	bool mcb_IMU_SPI  # IMU SPI Bus Transfer
	bool mcb_INS_Memory_Interface  # INS Memory Interface
	bool mcb_INS_Memory_Static_Data  # INS Memory Static Data
	bool mcb_IMU_Non_Comprehensive_RAM  # IMU Non-Comprehensive RAM
	bool mcb_INS_Temperature  # INS Temperature
	bool mcb_IMU_Loop_Completion  # IMU Loop Completion
	bool mcb_IMU_WDT  # IMU WDT
	bool mcb_IMU_Processor  # IMU Processor
	bool mcb_INS_Processor  # INS Processor
	bool mcb_Processor_Interrupt  # Processor Interrupt
	bool mcb_Frame_Timer  # Frame Timer
	bool mcb_Time_Tagging  # Time Tagging
	bool mcb_IMU_Stack_Overflow  # IMU Stack Overflow
	bool mcb_Power_Up_BIT_Timer  # Power Up BIT Timer
	bool mcb_INS_Stack_Overflow  # INS Stack Overflow
	bool mcb_Programmable_Logic_Read_Back  # Programmable Logic Read Back
	bool mcb_INS_Loop_Completion  # INS Loop Completion
	bool mcb_First_Stage_Boot_Loader  # First Stage Boot Loader
	bool mcb_Flash_Loader_Table  # Flash Loader Table
	bool mcb_Register_Initialization_Table  # Register Initialization Table
