# INS/GNSS System status summary
# Summary bits for each INS/GNSS sub-system. In case of fail, investigate specific sub-system BIT
# custom system_bit_summary_t
	bool Go_NoGo_BIT_Summary  # Go/No Go BIT Summary
	bool MPB_Subsystem_BIT_Summary  # MPB Subsystem BIT Summary
	bool GPS_Subsystem_BIT_Summary  # GPS Subsystem BIT Summary
	bool Gyro_Subsystem_BIT_Summary  # Gyro Subsystem BIT Summary
	bool Accelerometer_Subsystem_BIT_Summary  # Accelerometer Subsystem BIT Summary
	bool IMU_Subsystem_BIT_Summary  # IMU Subsystem BIT Summary
