# camera-specific config for 8380
# config here will override shared config
camera_top_center_front/camera_driver_nodelet:
  serial: 18481924
camera_top_left_front/camera_driver_nodelet:
  serial: 19073725
camera_top_right_front/camera_driver_nodelet:
  serial: 19095446
